// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB70NBvrpKh6o7KZHq7jKVdbwWb-skcrxQ',
    appId: '1:30882313876:web:9f6d950f9e22ea731f2681',
    messagingSenderId: '30882313876',
    projectId: 'hajed-cars',
    authDomain: 'hajed-cars.firebaseapp.com',
    storageBucket: 'hajed-cars.firebasestorage.app',
    measurementId: 'G-VGETKVR6R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUuU1-w5_l0qwpeFtyNokD7tj89-l-N6c',
    appId: '1:30882313876:android:b338af95f6e9e6291f2681',
    messagingSenderId: '30882313876',
    projectId: 'hajed-cars',
    storageBucket: 'hajed-cars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQjtWGgJ3ffrbY5mKQDGteYDFDY8v4dM',
    appId: '1:30882313876:ios:1fe7b912db473cd61f2681',
    messagingSenderId: '30882313876',
    projectId: 'hajed-cars',
    storageBucket: 'hajed-cars.firebasestorage.app',
    iosBundleId: 'com.Hajed.car',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQjtWGgJ3ffrbY5mKQDGteYDFDY8v4dM',
    appId: '1:30882313876:ios:c001f8e7a7d0c9d41f2681',
    messagingSenderId: '30882313876',
    projectId: 'hajed-cars',
    storageBucket: 'hajed-cars.firebasestorage.app',
    iosBundleId: 'com.example.car',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB70NBvrpKh6o7KZHq7jKVdbwWb-skcrxQ',
    appId: '1:30882313876:web:69f0030a3acf26981f2681',
    messagingSenderId: '30882313876',
    projectId: 'hajed-cars',
    authDomain: 'hajed-cars.firebaseapp.com',
    storageBucket: 'hajed-cars.firebasestorage.app',
    measurementId: 'G-YBW7MXR2RQ',
  );
}
