// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9zywupridWLT8Wr0IZW0Wzug3pqJ2EKQ',
    appId: '1:640250185998:android:f4dd04cec649a59777ef5f',
    messagingSenderId: '640250185998',
    projectId: 'cars-172a8',
    storageBucket: 'cars-172a8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu_urKSLYBsb23UUtSXRmLrjNbgt4m9TE',
    appId: '1:640250185998:ios:bf33a8e94686a22177ef5f',
    messagingSenderId: '640250185998',
    projectId: 'cars-172a8',
    storageBucket: 'cars-172a8.firebasestorage.app',
    iosBundleId: 'com.Hajed.car',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu_urKSLYBsb23UUtSXRmLrjNbgt4m9TE',
    appId: '1:640250185998:ios:cd34f0900749495d77ef5f',
    messagingSenderId: '640250185998',
    projectId: 'cars-172a8',
    storageBucket: 'cars-172a8.firebasestorage.app',
    iosBundleId: 'com.example.car',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbN6yOp5FsZReEx2UWK-DwzVVYNK-ifJk',
    appId: '1:640250185998:web:807f4f9bee069d2c77ef5f',
    messagingSenderId: '640250185998',
    projectId: 'cars-172a8',
    authDomain: 'cars-172a8.firebaseapp.com',
    storageBucket: 'cars-172a8.firebasestorage.app',
    measurementId: 'G-8K17XPMDQ1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbN6yOp5FsZReEx2UWK-DwzVVYNK-ifJk',
    appId: '1:640250185998:web:3ce82d30fdda059f77ef5f',
    messagingSenderId: '640250185998',
    projectId: 'cars-172a8',
    authDomain: 'cars-172a8.firebaseapp.com',
    storageBucket: 'cars-172a8.firebasestorage.app',
    measurementId: 'G-JDVWW7Y2MP',
  );
}
